export const mockDoctors = [
  {
    id: 'doc1',
    name: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    experience: '15',
    email: 'sarah.johnson@hospital.com',
    phone: '+1 234-567-8901',
    available: true,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
    timeSlots: ['9:00 AM', '10:00 AM', '11:00 AM', '2:00 PM', '3:00 PM', '4:00 PM'],
  },
  {
    id: 'doc2',
    name: 'Dr. Michael Chen',
    specialty: 'Pediatrics',
    experience: '12',
    email: 'michael.chen@hospital.com',
    phone: '+1 234-567-8902',
    available: true,
    availableDays: ['Monday', 'Wednesday', 'Thursday', 'Friday'],
    timeSlots: ['9:00 AM', '10:00 AM', '11:00 AM', '1:00 PM', '2:00 PM', '3:00 PM'],
  },
  {
    id: 'doc3',
    name: 'Dr. Emily Rodriguez',
    specialty: 'Dermatology',
    experience: '10',
    email: 'emily.rodriguez@hospital.com',
    phone: '+1 234-567-8903',
    available: true,
    availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '11:00 AM', '2:00 PM', '3:00 PM', '4:00 PM'],
  },
  {
    id: 'doc4',
    name: 'Dr. James Wilson',
    specialty: 'Orthopedics',
    experience: '20',
    email: 'james.wilson@hospital.com',
    phone: '+1 234-567-8904',
    available: false,
    availableDays: ['Monday', 'Tuesday', 'Thursday'],
    timeSlots: ['9:00 AM', '10:00 AM', '11:00 AM', '2:00 PM'],
  },
];

export const mockAppointments = [
  {
    id: 'apt1',
    patientId: 'pat1',
    patientName: 'John Doe',
    doctorId: 'doc1',
    doctorName: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    date: '2025-10-20',
    time: '10:00 AM',
    status: 'confirmed',
    createdAt: '2025-10-15T10:00:00Z',
  },
  {
    id: 'apt2',
    patientId: 'pat2',
    patientName: 'Jane Smith',
    doctorId: 'doc2',
    doctorName: 'Dr. Michael Chen',
    specialty: 'Pediatrics',
    date: '2025-10-18',
    time: '2:00 PM',
    status: 'completed',
    createdAt: '2025-10-10T14:00:00Z',
  },
  {
    id: 'apt3',
    patientId: 'pat3',
    patientName: 'Bob Johnson',
    doctorId: 'doc3',
    doctorName: 'Dr. Emily Rodriguez',
    specialty: 'Dermatology',
    date: '2025-10-22',
    time: '11:00 AM',
    status: 'confirmed',
    createdAt: '2025-10-16T11:00:00Z',
  },
  {
    id: 'apt4',
    patientId: 'pat1',
    patientName: 'John Doe',
    doctorId: 'doc4',
    doctorName: 'Dr. James Wilson',
    specialty: 'Orthopedics',
    date: '2025-10-19',
    time: '9:00 AM',
    status: 'cancelled',
    createdAt: '2025-10-12T09:00:00Z',
  },
];

export const mockPrescriptions = [
  {
    id: 'rx1',
    patientId: 'pat1',
    patientName: 'John Doe',
    doctorName: 'Dr. Sarah Johnson',
    date: '2025-10-15',
    medications: [
      {
        name: 'Aspirin',
        dosage: '100mg',
        frequency: 'Once daily',
        duration: '30 days',
      },
      {
        name: 'Atorvastatin',
        dosage: '20mg',
        frequency: 'Once daily at bedtime',
        duration: '30 days',
      },
    ],
    notes: 'Take with food. Monitor blood pressure regularly.',
  },
  {
    id: 'rx2',
    patientId: 'pat2',
    patientName: 'Jane Smith',
    doctorName: 'Dr. Michael Chen',
    date: '2025-10-12',
    medications: [
      {
        name: 'Amoxicillin',
        dosage: '250mg',
        frequency: 'Three times daily',
        duration: '7 days',
      },
    ],
    notes: 'Complete the full course of antibiotics even if symptoms improve.',
  },
];

export const mockPatients = [
  {
    id: 'pat1',
    name: 'John Doe',
    age: 45,
    gender: 'Male',
    allergies: ['Penicillin'],
    conditions: ['Hypertension', 'High Cholesterol'],
    visits: [
      {
        date: '2025-10-15',
        diagnosis: 'Hypertension Follow-up',
        treatment: 'Medication adjustment',
        notes: 'Blood pressure improving with current medication.',
      },
      {
        date: '2025-09-20',
        diagnosis: 'Annual Checkup',
        treatment: 'Routine examination',
        notes: 'All vitals within normal range.',
      },
    ],
  },
  {
    id: 'pat2',
    name: 'Jane Smith',
    age: 8,
    gender: 'Female',
    allergies: [],
    conditions: [],
    visits: [
      {
        date: '2025-10-12',
        diagnosis: 'Upper Respiratory Infection',
        treatment: 'Antibiotics prescribed',
        notes: 'Parents advised to monitor temperature.',
      },
    ],
  },
  {
    id: 'pat3',
    name: 'Bob Johnson',
    age: 32,
    gender: 'Male',
    allergies: ['Latex'],
    conditions: ['Eczema'],
    visits: [
      {
        date: '2025-10-08',
        diagnosis: 'Eczema Flare-up',
        treatment: 'Topical corticosteroid cream',
        notes: 'Recommended avoiding triggers like harsh soaps.',
      },
      {
        date: '2025-08-15',
        diagnosis: 'Skin Allergy Test',
        treatment: 'Allergy testing completed',
        notes: 'Positive for dust mites and pollen.',
      },
    ],
  },
];
